name = "norasol-website"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# This tells Cloudflare to serve static files from your main repository folder
[assets]
directory = "."
binding = "ASSETS"

[env.production]
name = "norasol-website-production"
routes = [
  { pattern = "norasol.workers.dev/*", zone_name = "workers.dev" }
]
